version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - dupl
    - gochecknoinits
    - gocritic
    - gocyclo
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - gosec
    - revive
    - gochecknoglobals
  disable:
    - lll
    - goconst
  settings:
    errcheck:
      ignore: fmt:.*

formatters:
  enable:
    - gofmt
    - goimports
