site_name: 'protoc-gen-event'
site_description: 'protoc plugin to publish protobuf messages with Watermill '

nav:
  - Home: index.md
  - Installation: installation.md
  - 'Defining events': defining-events.md
  - 'Enforcing validation rules': enforcing-validation-rules.md
  - 'Development': development.md

plugins:
  - techdocs-core
